version: '2'

services:
  app:
    build: .
    env_file:
        - .env
    container_name: gender_app
    ports:
      - $ACCESS_PORT:$ACCESS_PORT
    environment:
      TZ: 'Europe/Moscow'
      PYTHONUNBUFFERED: 0
      COUNT: $COUNT_NAMES
      ACCESS_NAME: $ACCESS_NAME
      ACCESS_PORT: $ACCESS_PORT
    command: >
          sh -c "gunicorn -w 4 --bind :$GUI_PORT app:app"  
